all: README.md

README.md: guessinggame.sh
	echo "## The Unixassignment" > README.md
	echo "*https://www.coursera.org/.*" >> README.md
	echo "\n* make a program called *guessinggame.sh*. request  user to guess the number of files in the current directoryThe user is informed if their guess is too high or too low.they should be congratulated when they guess correctly ." >> README.md
	echo -n "\n**Make date**: " >> README.md
	date >> README.md
	echo -n "Number of lines in guessinggame.sh:**" >> README.md
	grep -c ' ' guessinggame.sh >> README.md

